### ISSUE TITLE
Create blog post

### ISSUE THREAD

**Issue by krab7191** [christopher-dodge/storie#1]
This Epic consists of creating the functionality that allows a user to write a blog post and save it.

- [x] [Create a form component that allows a user to type in a blog post title, blog post body](https://github.com/christopher-dodge/storie/issues/2)
- [x] Create a frontend API call that POSTs the blog data to the backend
- [x] [Create a backend route that handles the POST request and stores the blog data in the database.](https://github.com/christopher-dodge/storie/issues/17)
